// **       LOS GETTERS SON:        **

// ** EL STATE ES REACTIVO Y CUANDO SE CAMBIA SE NOTIFICA 
// ** A TODOS LOS COMPONENTES DONDE ESTE ESCUCHANDO LOS CAMBIOS **


// export default () => ({
   
// })
